/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.21
 */

#ifndef _PyGnuplotWidgetAPI_H
#define _PyGnuplotWidgetAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_WebChannel
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_5_12_4


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_QtGnuplotEventReceiver 0
#define sipName_QtGnuplotEventReceiver &sipStrings_PyGnuplotWidget[0]
#define sipNameNr_QtGnuplotEventHandler 23
#define sipName_QtGnuplotEventHandler &sipStrings_PyGnuplotWidget[23]
#define sipNameNr_mouseDoubleClickEvent 45
#define sipName_mouseDoubleClickEvent &sipStrings_PyGnuplotWidget[45]
#define sipNameNr_focusPreviousChild 67
#define sipName_focusPreviousChild &sipStrings_PyGnuplotWidget[67]
#define sipNameNr_focusNextPrevChild 86
#define sipName_focusNextPrevChild &sipStrings_PyGnuplotWidget[86]
#define sipNameNr_destroySubWindows 105
#define sipName_destroySubWindows &sipStrings_PyGnuplotWidget[105]
#define sipNameNr_hasHeightForWidth 123
#define sipName_hasHeightForWidth &sipStrings_PyGnuplotWidget[123]
#define sipNameNr_mouseReleaseEvent 141
#define sipName_mouseReleaseEvent &sipStrings_PyGnuplotWidget[141]
#define sipNameNr_isSignalConnected 159
#define sipName_isSignalConnected &sipStrings_PyGnuplotWidget[159]
#define sipNameNr_senderSignalIndex 177
#define sipName_senderSignalIndex &sipStrings_PyGnuplotWidget[177]
#define sipNameNr_destroyOldWindow 195
#define sipName_destroyOldWindow &sipStrings_PyGnuplotWidget[195]
#define sipNameNr_initializeWindow 212
#define sipName_initializeWindow &sipStrings_PyGnuplotWidget[212]
#define sipNameNr_updateMicroFocus 229
#define sipName_updateMicroFocus &sipStrings_PyGnuplotWidget[229]
#define sipNameNr_contextMenuEvent 246
#define sipName_contextMenuEvent &sipStrings_PyGnuplotWidget[246]
#define sipNameNr_inputMethodEvent 263
#define sipName_inputMethodEvent &sipStrings_PyGnuplotWidget[263]
#define sipNameNr_inputMethodQuery 280
#define sipName_inputMethodQuery &sipStrings_PyGnuplotWidget[280]
#define sipNameNr_disconnectNotify 297
#define sipName_disconnectNotify &sipStrings_PyGnuplotWidget[297]
#define sipNameNr_QtGnuplotWidget 314
#define sipName_QtGnuplotWidget &sipStrings_PyGnuplotWidget[314]
#define sipNameNr_minimumSizeHint 330
#define sipName_minimumSizeHint &sipStrings_PyGnuplotWidget[330]
#define sipNameNr_mousePressEvent 346
#define sipName_mousePressEvent &sipStrings_PyGnuplotWidget[346]
#define sipNameNr_keyReleaseEvent 362
#define sipName_keyReleaseEvent &sipStrings_PyGnuplotWidget[362]
#define sipNameNr_PyGnuplotWidget 378
#define sipName_PyGnuplotWidget &sipStrings_PyGnuplotWidget[378]
#define sipNameNr_QtGnuplotScene 394
#define sipName_QtGnuplotScene &sipStrings_PyGnuplotWidget[394]
#define sipNameNr_focusNextChild 409
#define sipName_focusNextChild &sipStrings_PyGnuplotWidget[409]
#define sipNameNr_heightForWidth 424
#define sipName_heightForWidth &sipStrings_PyGnuplotWidget[424]
#define sipNameNr_dragLeaveEvent 439
#define sipName_dragLeaveEvent &sipStrings_PyGnuplotWidget[439]
#define sipNameNr_dragEnterEvent 454
#define sipName_dragEnterEvent &sipStrings_PyGnuplotWidget[454]
#define sipNameNr_mouseMoveEvent 469
#define sipName_mouseMoveEvent &sipStrings_PyGnuplotWidget[469]
#define sipNameNr_changedSignal 484
#define sipName_changedSignal &sipStrings_PyGnuplotWidget[484]
#define sipNameNr_sharedPainter 498
#define sipName_sharedPainter &sipStrings_PyGnuplotWidget[498]
#define sipNameNr_destroyWindow 512
#define sipName_destroyWindow &sipStrings_PyGnuplotWidget[512]
#define sipNameNr_thresholdTime 526
#define sipName_thresholdTime &sipStrings_PyGnuplotWidget[526]
#define sipNameNr_dragMoveEvent 540
#define sipName_dragMoveEvent &sipStrings_PyGnuplotWidget[540]
#define sipNameNr_keyPressEvent 554
#define sipName_keyPressEvent &sipStrings_PyGnuplotWidget[554]
#define sipNameNr_focusOutEvent 568
#define sipName_focusOutEvent &sipStrings_PyGnuplotWidget[568]
#define sipNameNr_connectNotify 300
#define sipName_connectNotify &sipStrings_PyGnuplotWidget[300]
#define sipNameNr_focusInEvent 582
#define sipName_focusInEvent &sipStrings_PyGnuplotWidget[582]
#define sipNameNr_initPainter 595
#define sipName_initPainter &sipStrings_PyGnuplotWidget[595]
#define sipNameNr_nativeEvent 607
#define sipName_nativeEvent &sipStrings_PyGnuplotWidget[607]
#define sipNameNr_actionEvent 619
#define sipName_actionEvent &sipStrings_PyGnuplotWidget[619]
#define sipNameNr_changeEvent 631
#define sipName_changeEvent &sipStrings_PyGnuplotWidget[631]
#define sipNameNr_tabletEvent 643
#define sipName_tabletEvent &sipStrings_PyGnuplotWidget[643]
#define sipNameNr_resizeEvent 655
#define sipName_resizeEvent &sipStrings_PyGnuplotWidget[655]
#define sipNameNr_paintEngine 667
#define sipName_paintEngine &sipStrings_PyGnuplotWidget[667]
#define sipNameNr_customEvent 679
#define sipName_customEvent &sipStrings_PyGnuplotWidget[679]
#define sipNameNr_eventFilter 691
#define sipName_eventFilter &sipStrings_PyGnuplotWidget[691]
#define sipNameNr_serverName 703
#define sipName_serverName &sipStrings_PyGnuplotWidget[703]
#define sipNameNr_enterEvent 714
#define sipName_enterEvent &sipStrings_PyGnuplotWidget[714]
#define sipNameNr_leaveEvent 725
#define sipName_leaveEvent &sipStrings_PyGnuplotWidget[725]
#define sipNameNr_constraint 736
#define sipName_constraint &sipStrings_PyGnuplotWidget[736]
#define sipNameNr_closeEvent 747
#define sipName_closeEvent &sipStrings_PyGnuplotWidget[747]
#define sipNameNr_repeatTime 758
#define sipName_repeatTime &sipStrings_PyGnuplotWidget[758]
#define sipNameNr_wheelEvent 769
#define sipName_wheelEvent &sipStrings_PyGnuplotWidget[769]
#define sipNameNr_columnSpan 780
#define sipName_columnSpan &sipStrings_PyGnuplotWidget[780]
#define sipNameNr_paintEvent 791
#define sipName_paintEvent &sipStrings_PyGnuplotWidget[791]
#define sipNameNr_setVisible 802
#define sipName_setVisible &sipStrings_PyGnuplotWidget[802]
#define sipNameNr_childEvent 813
#define sipName_childEvent &sipStrings_PyGnuplotWidget[813]
#define sipNameNr_timerEvent 824
#define sipName_timerEvent &sipStrings_PyGnuplotWidget[824]
#define sipNameNr_dropEvent 835
#define sipName_dropEvent &sipStrings_PyGnuplotWidget[835]
#define sipNameNr_hideEvent 845
#define sipName_hideEvent &sipStrings_PyGnuplotWidget[845]
#define sipNameNr_showEvent 855
#define sipName_showEvent &sipStrings_PyGnuplotWidget[855]
#define sipNameNr_moveEvent 865
#define sipName_moveEvent &sipStrings_PyGnuplotWidget[865]
#define sipNameNr_alignment 875
#define sipName_alignment &sipStrings_PyGnuplotWidget[875]
#define sipNameNr_receivers 885
#define sipName_receivers &sipStrings_PyGnuplotWidget[885]
#define sipNameNr_sizeHint 895
#define sipName_sizeHint &sipStrings_PyGnuplotWidget[895]
#define sipNameNr_property 904
#define sipName_property &sipStrings_PyGnuplotWidget[904]
#define sipNameNr_rowSpan 913
#define sipName_rowSpan &sipStrings_PyGnuplotWidget[913]
#define sipNameNr_destroy 921
#define sipName_destroy &sipStrings_PyGnuplotWidget[921]
#define sipNameNr_devType 929
#define sipName_devType &sipStrings_PyGnuplotWidget[929]
#define sipNameNr_enabled 937
#define sipName_enabled &sipStrings_PyGnuplotWidget[937]
#define sipNameNr_metric 945
#define sipName_metric &sipStrings_PyGnuplotWidget[945]
#define sipNameNr_window 952
#define sipName_window &sipStrings_PyGnuplotWidget[952]
#define sipNameNr_create 959
#define sipName_create &sipStrings_PyGnuplotWidget[959]
#define sipNameNr_sender 966
#define sipName_sender &sipStrings_PyGnuplotWidget[966]
#define sipNameNr_offset 973
#define sipName_offset &sipStrings_PyGnuplotWidget[973]
#define sipNameNr_system 980
#define sipName_system &sipStrings_PyGnuplotWidget[980]
#define sipNameNr_column 987
#define sipName_column &sipStrings_PyGnuplotWidget[987]
#define sipNameNr_object 994
#define sipName_object &sipStrings_PyGnuplotWidget[994]
#define sipNameNr_parent 1001
#define sipName_parent &sipStrings_PyGnuplotWidget[1001]
#define sipNameNr_roles 1008
#define sipName_roles &sipStrings_PyGnuplotWidget[1008]
#define sipNameNr_event 1014
#define sipName_event &sipStrings_PyGnuplotWidget[1014]
#define sipNameNr_mode 1020
#define sipName_mode &sipStrings_PyGnuplotWidget[1020]

#define sipMalloc                   sipAPI_PyGnuplotWidget->api_malloc
#define sipFree                     sipAPI_PyGnuplotWidget->api_free
#define sipBuildResult              sipAPI_PyGnuplotWidget->api_build_result
#define sipCallMethod               sipAPI_PyGnuplotWidget->api_call_method
#define sipCallProcedureMethod      sipAPI_PyGnuplotWidget->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_PyGnuplotWidget->api_call_error_handler
#define sipParseResultEx            sipAPI_PyGnuplotWidget->api_parse_result_ex
#define sipParseResult              sipAPI_PyGnuplotWidget->api_parse_result
#define sipParseArgs                sipAPI_PyGnuplotWidget->api_parse_args
#define sipParseKwdArgs             sipAPI_PyGnuplotWidget->api_parse_kwd_args
#define sipParsePair                sipAPI_PyGnuplotWidget->api_parse_pair
#define sipInstanceDestroyed        sipAPI_PyGnuplotWidget->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_PyGnuplotWidget->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_PyGnuplotWidget->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_PyGnuplotWidget->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_PyGnuplotWidget->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_PyGnuplotWidget->api_convert_to_void_ptr
#define sipAddException             sipAPI_PyGnuplotWidget->api_add_exception
#define sipNoFunction               sipAPI_PyGnuplotWidget->api_no_function
#define sipNoMethod                 sipAPI_PyGnuplotWidget->api_no_method
#define sipAbstractMethod           sipAPI_PyGnuplotWidget->api_abstract_method
#define sipBadClass                 sipAPI_PyGnuplotWidget->api_bad_class
#define sipBadCatcherResult         sipAPI_PyGnuplotWidget->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_PyGnuplotWidget->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_PyGnuplotWidget->api_bad_operator_arg
#define sipTrace                    sipAPI_PyGnuplotWidget->api_trace
#define sipTransferBack             sipAPI_PyGnuplotWidget->api_transfer_back
#define sipTransferTo               sipAPI_PyGnuplotWidget->api_transfer_to
#define sipTransferBreak            sipAPI_PyGnuplotWidget->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_PyGnuplotWidget->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_PyGnuplotWidget->api_wrapper_type
#define sipWrapperType_Type         sipAPI_PyGnuplotWidget->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_PyGnuplotWidget->api_voidptr_type
#define sipGetPyObject              sipAPI_PyGnuplotWidget->api_get_pyobject
#define sipGetAddress               sipAPI_PyGnuplotWidget->api_get_address
#define sipGetMixinAddress          sipAPI_PyGnuplotWidget->api_get_mixin_address
#define sipGetCppPtr                sipAPI_PyGnuplotWidget->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_PyGnuplotWidget->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_PyGnuplotWidget->api_is_py_method
#define sipCallHook                 sipAPI_PyGnuplotWidget->api_call_hook
#define sipEndThread                sipAPI_PyGnuplotWidget->api_end_thread
#define sipConnectRx                sipAPI_PyGnuplotWidget->api_connect_rx
#define sipDisconnectRx             sipAPI_PyGnuplotWidget->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_PyGnuplotWidget->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_PyGnuplotWidget->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_PyGnuplotWidget->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_PyGnuplotWidget->api_add_type_instance
#define sipFreeSipslot              sipAPI_PyGnuplotWidget->api_free_sipslot
#define sipSameSlot                 sipAPI_PyGnuplotWidget->api_same_slot
#define sipPySlotExtend             sipAPI_PyGnuplotWidget->api_pyslot_extend
#define sipConvertRx                sipAPI_PyGnuplotWidget->api_convert_rx
#define sipAddDelayedDtor           sipAPI_PyGnuplotWidget->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_PyGnuplotWidget->api_can_convert_to_type
#define sipConvertToType            sipAPI_PyGnuplotWidget->api_convert_to_type
#define sipForceConvertToType       sipAPI_PyGnuplotWidget->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_PyGnuplotWidget->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_PyGnuplotWidget->api_convert_to_enum
#define sipConvertToBool            sipAPI_PyGnuplotWidget->api_convert_to_bool
#define sipReleaseType              sipAPI_PyGnuplotWidget->api_release_type
#define sipConvertFromType          sipAPI_PyGnuplotWidget->api_convert_from_type
#define sipConvertFromNewType       sipAPI_PyGnuplotWidget->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_PyGnuplotWidget->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_PyGnuplotWidget->api_convert_from_enum
#define sipGetState                 sipAPI_PyGnuplotWidget->api_get_state
#define sipExportSymbol             sipAPI_PyGnuplotWidget->api_export_symbol
#define sipImportSymbol             sipAPI_PyGnuplotWidget->api_import_symbol
#define sipFindType                 sipAPI_PyGnuplotWidget->api_find_type
#define sipFindNamedEnum            sipAPI_PyGnuplotWidget->api_find_named_enum
#define sipBytes_AsChar             sipAPI_PyGnuplotWidget->api_bytes_as_char
#define sipBytes_AsString           sipAPI_PyGnuplotWidget->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_PyGnuplotWidget->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_PyGnuplotWidget->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_PyGnuplotWidget->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_PyGnuplotWidget->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_PyGnuplotWidget->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_PyGnuplotWidget->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_PyGnuplotWidget->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_PyGnuplotWidget->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_PyGnuplotWidget->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_PyGnuplotWidget->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_PyGnuplotWidget->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_PyGnuplotWidget->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_PyGnuplotWidget->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_PyGnuplotWidget->api_save_slot
#define sipClearAnySlotReference    sipAPI_PyGnuplotWidget->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_PyGnuplotWidget->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_PyGnuplotWidget->api_deprecated
#define sipGetReference             sipAPI_PyGnuplotWidget->api_get_reference
#define sipKeepReference            sipAPI_PyGnuplotWidget->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_PyGnuplotWidget->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_PyGnuplotWidget->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_PyGnuplotWidget->api_type_from_py_type_object
#define sipTypeScope                sipAPI_PyGnuplotWidget->api_type_scope
#define sipResolveTypedef           sipAPI_PyGnuplotWidget->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_PyGnuplotWidget->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_PyGnuplotWidget->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_PyGnuplotWidget->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_PyGnuplotWidget->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_PyGnuplotWidget->api_enable_overflow_checking
#define sipInitMixin                sipAPI_PyGnuplotWidget->api_init_mixin
#define sipExportModule             sipAPI_PyGnuplotWidget->api_export_module
#define sipInitModule               sipAPI_PyGnuplotWidget->api_init_module
#define sipGetInterpreter           sipAPI_PyGnuplotWidget->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_PyGnuplotWidget->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_PyGnuplotWidget->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_PyGnuplotWidget->api_get_type_user_data
#define sipPyTypeDict               sipAPI_PyGnuplotWidget->api_py_type_dict
#define sipPyTypeName               sipAPI_PyGnuplotWidget->api_py_type_name
#define sipGetCFunction             sipAPI_PyGnuplotWidget->api_get_c_function
#define sipGetMethod                sipAPI_PyGnuplotWidget->api_get_method
#define sipFromMethod               sipAPI_PyGnuplotWidget->api_from_method
#define sipGetDate                  sipAPI_PyGnuplotWidget->api_get_date
#define sipFromDate                 sipAPI_PyGnuplotWidget->api_from_date
#define sipGetDateTime              sipAPI_PyGnuplotWidget->api_get_datetime
#define sipFromDateTime             sipAPI_PyGnuplotWidget->api_from_datetime
#define sipGetTime                  sipAPI_PyGnuplotWidget->api_get_time
#define sipFromTime                 sipAPI_PyGnuplotWidget->api_from_time
#define sipIsUserType               sipAPI_PyGnuplotWidget->api_is_user_type
#define sipGetFrame                 sipAPI_PyGnuplotWidget->api_get_frame
#define sipCheckPluginForType       sipAPI_PyGnuplotWidget->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_PyGnuplotWidget->api_unicode_new
#define sipUnicodeWrite             sipAPI_PyGnuplotWidget->api_unicode_write
#define sipUnicodeData              sipAPI_PyGnuplotWidget->api_unicode_data
#define sipGetBufferInfo            sipAPI_PyGnuplotWidget->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_PyGnuplotWidget->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_PyGnuplotWidget->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_PyGnuplotWidget->api_is_derived_class
#define sipGetUserObject            sipAPI_PyGnuplotWidget->api_get_user_object
#define sipSetUserObject            sipAPI_PyGnuplotWidget->api_set_user_object
#define sipRegisterEventHandler     sipAPI_PyGnuplotWidget->api_register_event_handler
#define sipLong_AsChar              sipAPI_PyGnuplotWidget->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_PyGnuplotWidget->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_PyGnuplotWidget->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_PyGnuplotWidget->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_PyGnuplotWidget->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_PyGnuplotWidget->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_PyGnuplotWidget->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_PyGnuplotWidget->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_PyGnuplotWidget->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_PyGnuplotWidget->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_PyGnuplotWidget->api_long_as_unsigned_long_long
#define sipLong_AsSizeT             sipAPI_PyGnuplotWidget->api_long_as_size_t
#define sipVisitWrappers            sipAPI_PyGnuplotWidget->api_visit_wrappers
#define sipRegisterExitNotifier     sipAPI_PyGnuplotWidget->api_register_exit_notifier

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_PyGnuplotWidget->api_map_string_to_class
#define sipMapIntToClass            sipAPI_PyGnuplotWidget->api_map_int_to_class
#define sipFindClass                sipAPI_PyGnuplotWidget->api_find_class
#define sipFindMappedType           sipAPI_PyGnuplotWidget->api_find_mapped_type
#define sipConvertToArray           sipAPI_PyGnuplotWidget->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_PyGnuplotWidget->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_PyGnuplotWidget->api_enable_gc
#define sipPrintObject              sipAPI_PyGnuplotWidget->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_PyGnuplotWidget->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_PyGnuplotWidget[];

#define sipType_QtGnuplotEventReceiver sipExportedTypes_PyGnuplotWidget[1]
#define sipClass_QtGnuplotEventReceiver sipExportedTypes_PyGnuplotWidget[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyGnuplotWidget_QtGnuplotEventReceiver;

#define sipType_QtGnuplotEventHandler sipExportedTypes_PyGnuplotWidget[0]
#define sipClass_QtGnuplotEventHandler sipExportedTypes_PyGnuplotWidget[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyGnuplotWidget_QtGnuplotEventHandler;

#define sipType_QtGnuplotScene sipExportedTypes_PyGnuplotWidget[2]
#define sipClass_QtGnuplotScene sipExportedTypes_PyGnuplotWidget[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyGnuplotWidget_QtGnuplotScene;

#define sipType_QtGnuplotWidget sipExportedTypes_PyGnuplotWidget[3]
#define sipClass_QtGnuplotWidget sipExportedTypes_PyGnuplotWidget[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyGnuplotWidget_QtGnuplotWidget;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_PyGnuplotWidget;
extern sipExportedModuleDef sipModuleAPI_PyGnuplotWidget;
extern sipTypeDef *sipExportedTypes_PyGnuplotWidget[];

#define sipType_Qt_InputMethodQuery sipImportedTypes_PyGnuplotWidget_QtCore[9].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_PyGnuplotWidget_QtCore[9].it_td->u.td_py_type

#define sipType_QObject sipImportedTypes_PyGnuplotWidget_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_PyGnuplotWidget_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_PyGnuplotWidget_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_PyGnuplotWidget_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_PyGnuplotWidget_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_PyGnuplotWidget_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_PyGnuplotWidget_QtCore[7].it_td
#define sipClass_QTimerEvent sipImportedTypes_PyGnuplotWidget_QtCore[7].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_PyGnuplotWidget_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_PyGnuplotWidget_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_PyGnuplotWidget_QtCore[3].it_td
#define sipClass_QMetaMethod sipImportedTypes_PyGnuplotWidget_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_PyGnuplotWidget_QtCore[5].it_td
#define sipClass_QSize sipImportedTypes_PyGnuplotWidget_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_PyGnuplotWidget_QtCore[8].it_td
#define sipClass_QVariant sipImportedTypes_PyGnuplotWidget_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QString sipImportedTypes_PyGnuplotWidget_QtCore[6].it_td

#define sipType_quintptr sipImportedTypes_PyGnuplotWidget_QtCore[10].it_td
extern sipImportedTypeDef sipImportedTypes_PyGnuplotWidget_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_PyGnuplotWidget_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_PyGnuplotWidget_QtGui[13].it_td
#define sipClass_QPaintDevice sipImportedTypes_PyGnuplotWidget_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_PyGnuplotWidget_QtGui[14].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_PyGnuplotWidget_QtGui[14].it_td->u.td_py_type

#define sipType_QMouseEvent sipImportedTypes_PyGnuplotWidget_QtGui[11].it_td
#define sipClass_QMouseEvent sipImportedTypes_PyGnuplotWidget_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_PyGnuplotWidget_QtGui[21].it_td
#define sipClass_QWheelEvent sipImportedTypes_PyGnuplotWidget_QtGui[21].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_PyGnuplotWidget_QtGui[20].it_td
#define sipClass_QTabletEvent sipImportedTypes_PyGnuplotWidget_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_PyGnuplotWidget_QtGui[10].it_td
#define sipClass_QKeyEvent sipImportedTypes_PyGnuplotWidget_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_PyGnuplotWidget_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_PyGnuplotWidget_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_PyGnuplotWidget_QtGui[16].it_td
#define sipClass_QPaintEvent sipImportedTypes_PyGnuplotWidget_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_PyGnuplotWidget_QtGui[12].it_td
#define sipClass_QMoveEvent sipImportedTypes_PyGnuplotWidget_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_PyGnuplotWidget_QtGui[18].it_td
#define sipClass_QResizeEvent sipImportedTypes_PyGnuplotWidget_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_PyGnuplotWidget_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_PyGnuplotWidget_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_PyGnuplotWidget_QtGui[19].it_td
#define sipClass_QShowEvent sipImportedTypes_PyGnuplotWidget_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_PyGnuplotWidget_QtGui[8].it_td
#define sipClass_QHideEvent sipImportedTypes_PyGnuplotWidget_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_PyGnuplotWidget_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_PyGnuplotWidget_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_PyGnuplotWidget_QtGui[9].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_PyGnuplotWidget_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_PyGnuplotWidget_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_PyGnuplotWidget_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_PyGnuplotWidget_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_PyGnuplotWidget_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_PyGnuplotWidget_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_PyGnuplotWidget_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_PyGnuplotWidget_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_PyGnuplotWidget_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_PyGnuplotWidget_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_PyGnuplotWidget_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_PyGnuplotWidget_QtGui[17].it_td
#define sipClass_QPainter sipImportedTypes_PyGnuplotWidget_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_PyGnuplotWidget_QtGui[15].it_td
#define sipClass_QPaintEngine sipImportedTypes_PyGnuplotWidget_QtGui[15].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_PyGnuplotWidget_QtGui[];

#define sipType_QWidget sipImportedTypes_PyGnuplotWidget_QtWidgets[0].it_td
#define sipClass_QWidget sipImportedTypes_PyGnuplotWidget_QtWidgets[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_PyGnuplotWidget_QtWidgets[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_PyGnuplotWidget_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_PyGnuplotWidget_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_PyGnuplotWidget_qt_metacast;

#endif
